language: node_js
sudo: false
node_js:
  - "stable"
  - "0.12"
  - "0.10"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - export CXX=g++-4.8
  - $CXX --version
install:
  - npm install